queue_rules:
  - name: default
    queue_conditions:
      - base=master
      - label=merge-queue
    merge_conditions:
      - check-success=buildbot/nix-eval
    merge_method: rebase

pull_request_rules:
  - name: merge using the merge queue
    conditions: []
    actions:
      queue:
